import { Inter } from "next/font/google";
import "./globals.css";
import MainContainer from "@/containers/MainContainer/MainContainer";
import SidebarComponent from "@/components/global/sidebar";
import { Box } from "@mui/material";
import TopbarComponent from "@/components/global/topbar";
import SidebarContainer from "@/containers/sidebarContainer";
import ModalWrapper from "@/containers/ModalWrapper";
import SpinnerComponent from "@/components/global/spinner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }}>
          <TopbarComponent />
          <SidebarContainer>
            <SidebarComponent />
          </SidebarContainer>
          <MainContainer>{children}</MainContainer>
        </Box>
        <ModalWrapper />
        <SpinnerComponent />
      </body>
    </html>
  );
}
